# com.github.paguos.knime.nodes.penguin: # {group_id}.{name} from the knime.yml
#   src: /Users/pabloosinaga/Development/knime-labs/penguin # Path to folder containing the extension files
#   conda_env_path: /Users/pabloosinaga/opt/miniconda3/envs/knime-labs-penguin-env
#   debug_mode: true # Optional line, if set to true, it will always use the latest changes of execute/configure, when that method is used within the KNIME Analytics Platform
com.github.paguos.knime.labs.understats:
  src: /Users/pabloosinaga/Development/knime-labs/understats
  conda_env_path: /Users/pabloosinaga/opt/miniconda3/envs/knime-labs-understats-env
  debug_mode: true 
org.tutorial.first_extension: # {group_id}.{name} from the knime.yml
  src: /Users/pabloosinaga/Development/knime-labs/tutorial_extension # Path to folder containing the extension files
  conda_env_path: /Users/pabloosinaga/opt/miniconda3/envs/my_python_env # Path to the Python environment to use
  debug_mode: true # Optional line, if set to true, it will always use the latest changes of execute/configure, when that method is used within the KNIME Analytics Platform
