name: knime-labs-understats-env
channels:
  - knime
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - knime-extension
  - knime-python-base=4.6
  - aiohttp=3.7.4
  - autopep8
  - flake8
  - pytest=6.2.0
